### ISSUE TITLE
#include <RotaryEncoderAdvanced.cpp> //for some reason linker can't find the *.cpp :(

### ISSUE THREAD

**Issue by yet-another-average-joe** [enjoyneering/RotaryEncoder#3]
Hello, and thanks for this library !

In the examples, you include RotaryEncoderAdvanced.cpp

Templates have to live in header files (inline functions only). The contents of RotaryEncoderAdvanced.cpp should be declared in RotaryEncoderAdvanced.h, and not in a separate cpp file that will never get compiled. Never compiled = never linked. (the preprocessor cannot know what type to use, it is defined in another file) 

In a template class, everything must be in one file. (usually, the functions are defined in the class itself, not outside)

Have a look to the STL : no cpp files ! Only headers (that don't even have the h or hpp extension, but gcc does not like files with no extension)

Therefore everything has to be in RotaryEncoderAdvanced.h, and  RotaryEncoderAdvanced.cpp has to be removed. And it will compile and link just fine

I modified your code and repacked it : 
[RotaryEncoder.zip](https://github.com/enjoyneering/RotaryEncoder/files/3430871/RotaryEncoder.zip)

**Comment by enjoyneering** [comment]
Thank you for fix. I have a question. Why linker can compile RotaryEncoder.h & RotaryEncoder.cpp?

**Comment by yet-another-average-joe** [comment]
Hard to explain,  english is not my first langage. 

First of all, I made a mistake : templates are expanded by the compiler, not the preprocessor ! But they work similarly. (I had to verify on the web, because I learned templates long ago and don't know where is my Bjarne Stroustrup reference book). Thinking of templates as macros (they are not !) made things easy for me, and I forgot about the reality ! (and it seems many people do the same mistake)

I found this : 

"When the compiler sees the definition of a template, it does not generate code. It generates code only when we instantiate a specific instance of the template. The fact that code is generated only when we use a template (and not when we define it) affects how we organize our source code and when errors are detected...To generate an instantiation, the compiler needs to have the code that defines a function template or class template member function. As a result, unlike non-template code, headers for templates typically include definitions as well as declarations."

For the compiler to compile a template class and its functions, it has to know the type. The cpp file (RotaryEncoderAdvanced.cpp) does not contain any type, nor its header. The compiler will not search for a corresponding cpp file. This behaviour is by conception. A template cpp file compiles to nothing.

The templates are somewhat similar to macros. Imagine you are declaring macros in a cpp file and attempt to use them in another cpp file : it will not work ! The file will not give an obj file to link with other ones. When you included cpp in the example files, you gave the compiler the definitions it needed and it was able to create the typed class and member function into the exemple file obj (the example file is compiled to one unique obj file, and must contain the whole code for the template class).

In theory, there's no problem declaring template functions in separate cpp files. It's not usual (I never encountered this...), but it could be useful. If one wants to do this, he has to #include the cpp file at the very end of the header. You could also do this...

Usually, member functions are declared between the class brackets : it makes code much easier to read and maintain : no "<TYPE>" soup evrywhere, as you can see !

(I'm not a great fan of templates, as they can be a nightmare to debug ! But they can be very usefull)

**Comment by enjoyneering** [comment]
russian??

**Comment by yet-another-average-joe** [comment]
:)))))))))))))

french !

**Comment by proddy** [comment]
LOL!

**Comment by enjoyneering** [comment]
LOL! is very rare language, but I know it. :))))

yet-another-average-joe do you know if there is a standard for what should be in the header file and what should be in the source file? Thank you in advance.

**Comment by yet-another-average-joe** [comment]
Everything that contains <TYPE> in the declaration and/or definition has to be in the header. Rule of thumb. No cpp files.

cpp files are only for instanciation (application code).

The reference book is "The C++ Programming Language", by Bjarne Stroustrup (the creator of the C++ language). Templates were introduced in 1985 and described in the 1st edition of this book. This book is expensive, but a used one, not too old (10 or 20 years), will be good enough. It is the reference and a must have. It is the equivalent of the Kernighan and Ritchie (C language)

Keep in mind that templates can cause many problems and are really hard to debug. They are also generally memory hogs with dynamic memory allocation (and cause fragmentation). I'm actually fighting with the Arduino STL : it does not compile in all development environments, and don't know where bug reports have to be issued ! (STL is great on PCs)

**Comment by proddy** [comment]
@yet-another-average-joe  yes, that's a very good practice to use .hpp files for classes. I learned a lot from looking at how [ArduinoJson](https://github.com/bblanchon/ArduinoJson) approached this.

@enjoyneering I use the RotaryEncoder library too with an ESP32. I made some small modifications  but essentially its still a class library with one .cpp and an .h, and it compiles and works fine.

I'm not Russian or French btw ;-)

**Comment by enjoyneering** [comment]
Thanks for the help guys. I'm not a programmer, microcontrollers is my hobby and I just started learning classes, templates... Now I am stuck with pointers and links - I can not understand them. I will read the book and promise to fix the library, but I don’t know when. Maybe around christmas time..

proddy you are from Netherlands!!! According to google you have 5 official landuages - Dutch, Papiamento, Yiddish, English, Frisian.

By the way guys your english is good.
