### ISSUE TITLE
RotaryEncoder 

### ISSUE THREAD

**Issue by Beerlesklopfer** [enjoyneering/RotaryEncoder#4]
You declared allmost all getters / setter as inline but impemnted them in a seperate *.cpp file; so the linker fails! Maybe you will change the header like that:

```
    RotaryEncoder(uint8_t encoderA, uint8_t encoderB, uint8_t encoderButton);
           void     begin(void);
           void     readAB(void);
           void     readPushButton(void);

           int16_t  getPosition(void);
           bool     getPushButton(void);

           void     setPosition(int16_t position);
           void     setPushButton(bool state);
```
... and ...

```
    RotaryEncoderAdvanced(uint8_t encoderA, uint8_t encoderB, uint8_t encoderButton, T stepsPerClick, T minValue, T maxValue);

           T    getValue(void);
           void setValue(T value);

           T    getStepsPerClick(void);
           void setStepsPerClick(T value);

           T    getMinValue(void);
           void setMinValue(T value);

           T    getMaxValue(void);
            void setMaxValue(T value);

           void setValues(T currValue, T stepsPerClick, T minValue, T maxValue);

```

So the compiler succeeds. Otherwise transfer the code into the header, please.

Thak's for your patience!

Joerg

**Comment by enjoyneering** [comment]
Hi Beerlesklopfer,

I did, and the linker still does not work - have to include <RotaryEncoderAdvanced.cpp> in the sketch to work around the problem.

**Comment by thijstriemstra** [comment]
I'm testing `STM32RotaryEncoderInterruptsSerial.ino` and get:

```
.pio/libdeps/lolin32/RotaryEncoder_ID5568/src/RotaryEncoder.h:95:21: warning: inline function 'int16_t RotaryEncoder::getPosition()' used but never defined
     inline int16_t  getPosition(void);
```

And then this error:

```
.pio/build/lolin32/lib36b/libKY040_RotaryEncoderESP32.a(KY040_RotaryEncoderESP32.cpp.o): In function `KY040_RotaryEncoderESP32::loop()':
/home/foo/bar/KY040_RotaryEncoderESP32/KY040_RotaryEncoderESP32.cpp:50: undefined reference to `RotaryEncoder::getPosition()
```

platformio.ini:

```
[env:lolin32]
platform = espressif32
board = lolin32
framework = arduino

lib_deps =
  5568 ; RotaryEncoder
```

For some reason `getPosition` isn't included... Is this related to this issue?

>  have to include <RotaryEncoderAdvanced.cpp> in the sketch to work around the problem.

I'll try this.

**Comment by thijstriemstra** [comment]
> I'll try this.

Didn't work but removing `inline` from `int16_t  getPosition(void);` in `RotaryEncoder.h` did seem to work, things compile now. Should I make a pull request for that @enjoyneering?

**Comment by thijstriemstra** [comment]
> Should I make a pull request for that @enjoyneering?

Damn, it's fixed in the master branch. Hmm, why did it install old code..

Can you push a new release @enjoyneering?

**Comment by enjoyneering** [comment]
Hi,

Never done it before. For some reason i got an error - we weren’t able to create the release for you. Please correct the errors below.

**Comment by thijstriemstra** [comment]
@enjoyneering you need to create a new github tag (after bumping version nr) and that should be enough afaik.
