### ISSUE TITLE
Reading position with 24 step resolution

### ISSUE THREAD

**Issue by josh-gaby** [enjoyneering/RotaryEncoder#5]
Position readings with a 24 step resolution encoder aren't working but a 12 step resolution encoder from the same manufacturer / series works fine with the same code.

Using a blue pill and a BOURNS PEC12R-4130F-S0012 rotary encoder works fine but I accidentally ordered a bunch of the 24 step variation (BOURNS PEC12R-4230F-S0024), the closest I can get them to working is by un-commenting the '2 counts per click' for the fast MCU (lines 139 + 149 in  RotaryEncoder.cpp) but this results in the position jumping between 0 and 1. 

The data sheet for both is [here](https://datasheet.lcsc.com/szlcsc/1806141832_BOURNS-PEC12R-4230F-S0024_C143818.pdf) if that is any help.

Any help you could give would be much appreciated.

**Comment by proddy** [comment]
I had similar problems using a [SparkFun RGB Rotary Encoder](https://www.sparkfun.com/products/15141) with 24 pulses on an ESP32. I ended up modifying and merging with a different [library](https://github.com/igorantolic/ai-esp32-rotary-encoder). I can share it on gist if you're interested.

**Comment by josh-gaby** [comment]
That would be great if you could, its taking about 3 or 4 weeks for new parts to get here at the moment

**Comment by proddy** [comment]
> That would be great if you could, its taking about 3 or 4 weeks for new parts to get here at the moment

https://gist.github.com/proddy/7309c6beabb297682a304e8f6b8d43d0

**Comment by josh-gaby** [comment]
> 
> 
> > That would be great if you could, its taking about 3 or 4 weeks for new parts to get here at the moment
> 
> https://gist.github.com/proddy/7309c6beabb297682a304e8f6b8d43d0

Thanks for that, I'll give it ago later today.
