### ISSUE TITLE
is it possible to use with e6b2-cwz1x (incremental) ?

### ISSUE THREAD

**Issue by zoldaten** [enjoyneering/RotaryEncoder#9]
i`m working on e6b2-cwz1x (incremental) which fast continuously rotates.
as the speed is very fast arduino uno starts drops ticks in serial console.
so i moved to nodemcu v.3 and found this library.
can it helps ? how to adapt the code ?

**Comment by enjoyneering** [comment]
Arduino AVR "digitalRead()" is so slow
